/* ══════════════════════════════════════════════════════════
   FACULTY ALLOW-LIST
   Used by the Faculty (Certificate of Appreciation) pages to
   verify that the name entered belongs to a registered faculty
   member before allowing a download.

   HOW TO UPDATE:
   - List one full name per line inside the array below.
   - Do NOT include "Dr." — that is added automatically.
   - Matching ignores case, extra spaces, and periods, so
     "Ramyajit Lahiri", "ramyajit   lahiri", and "Ramyajit Lahiri "
     are all treated as the same name.
   - This same list is shared by every Faculty page (Neuro
     Emergency Workshop + TOXCODE 2026). If a person is faculty
     at only one of the workshops, that's fine — the organizer
     is responsible for sharing the right certificate link with
     the right people.
   ══════════════════════════════════════════════════════════ */

window.FACULTY_LIST = [
  "AN Mukherjee",
  "Aditi Aikat",
  "Aditya Vikram Ruia",
  "Agniva Maiti",
  "Aliva Pradhan",
  "Amir Raza",
  "Amit Bhowmik",
  "Amlan Dutta",
  "Anindya Dasgupta",
  "Anish Banerjee",
  "Ankita Saha",
  "Ankur Varma",
  "Aparajita Mitra",
  "Aparajita Priyadarsini",
  "Apurba Panja",
  "Arijit Sil",
  "Asif Iqbal S K",
  "Asim Kandar",
  "Abhishek Kumar Jaiswal",
  "Avishek Kumar",
  "Avishek Roy",
  "Basant saurabh",
  "Benazir Mahrein",
  "Bikram Das",
  "Biswa Ranjan Samal",
  "Bodhisatwa Choudhuri",
  "Christina Kongkham",
  "Debang Borah",
  "Debanjana Mukherjee",
  "Debanu Das",
  "Dipankar Saha",
  "Diya Saha",
  "Faiz",
  "I K Tiwary",
  "Indranil Mitra",
  "Indranil Das",
  "Jayanta Das",
  "Johnson K Vargese",
  "Kumar Raj",
  "Lakshmi Kangjam",
  "Mainak Majumdar",
  "Maitrayee Mukherjee",
  "Malay Mishra",
  "Manjeet Kaur",
  "Manoj Khemani",
  "Manoj Kumar",
  "Md Imran",
  "Nishant Agarwal",
  "Paromita Chakraborty",
  "Paromita Kanjilal Chakraborty",
  "Paramita Kanjilal Chakraborty",
  "Paramita Trivedi",
  "Partha Sarathi Biswal",
  "Pranesh Sarkar",
  "Purusatyam Chakraborty",
  "Rahul Anand",
  "Ramyajit Lahiri",
  "Ranjan Dutta",
  "Rudraneel Kumar",
  "Sai Surendar",
  "Saibal Moitra",
  "Samarth Acharyya",
  "Samata Chororia",
  "Sandeep Gore",
  "Sanjukta Dutta",
  "Santosh Singh",
  "Saptarshi Ghosh",
  "Saraswat Mitra",
  "Sayan Misra",
  "Sayantan Ghara",
  "Shefali Sharma",
  "Shiva Shankar Bhadra",
  "Shraya Palit Dawn",
  "Shweta Tyagi",
  "Shyam Singh",
  "Sidhhartha Basu",
  "Smita Moitra",
  "Soumitra Shankar Dutta",
  "Soumya Sengupta",
  "Sourabh Pathak",
  "Souvik Goswami",
  "Shree Sowjanya Patibandla",
  "Sowjanya Shree Patibandla",
  "Srinath KS",
  "Subhadeep Gupta",
  "Subham Saha",
  "Subhendu Das",
  "Sudhakar Reddy",
  "Sudip Banerjee",
  "Sudip Chakraborty",
  "Sudip Ghosh",
  "Sudipta Saha",
  "Sujit Singh",
  "Sujoy Das Thakur",
  "Suresh MVN",
  "Sushil Kumar",
  "Susmeet Mishra",
  "Suvadip Maity",
  "Swanay Mondal",
  "Talha Hussain",
  "Tarak Nath Das",
  "V P Chandrasekhar",
  "Venugopal PP",
  "Vikrant Chauhan",
  "Vishal Vaibhaw"
]
